#!/bin/bash
set -eux


REPO="charlesreid1/super-shitty-simple-static-site-generator"


function i-suck-at-python {
    python3 -m venv .venv
    ./.venv/bin/python3 -m pip install markdown
}

function gimme-pages {
    rm -fr output
    git clone git@github.com:${REPO}.git output/
    rm -fr output/*
    (
    cd output/
    git checkout --orphan gh-pages
    cat << EOF > index.html
<h2>hello world</h2>
EOF
    git add index.html
    git commit index.html -m 'Start some shit'
    git push origin gh-pages
    )
    rm -fr output/
}


function build {
    mkdir -p output/
    ./.venv/bin/python3 make_super_shitty_site.py
}

function serve {
    build
    (
    cd output
    python -m http.server 8000
    )
}

function deploy {
    set +x
    # This function is a piece of shit. FYI.
    rm -fr output/
    # Change this to your own fucking repo, asshole.
    git clone -b gh-pages git@github.com:${REPO}.git output
    rm -fr output/*
    echo "About to generate the shit out of this shitty content..."

    build

    (
    echo "Adding your new shit to your git shit..."
    cd output/
    git add -A .
    git commit -a -m "Automatic fucking deploy, asshole, out of the way - it's $(date -u +"%Y-%m-%d-%H-%M-%S")"
    git push origin gh-pages
    RESULT=$?
    if [ $RESULT -eq 0 ]; then
        echo "All your shit is in git. Congratu-fucking-lations."
    else
        echo "None of your shit is in git. The FUCk, git? Cleaning up some shit, hang on."
        #echo rm -fr output
        exit 1
    fi
    )
    echo "Fuck it I'm outta here"
}

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

"$@"
